### ISSUE TITLE
Failed copy build dll to output

### ISSUE THREAD

**Issue by thelostroot** [lepoco/CUDAfy.NET#1]
In new clone project "Rebuild solution" fail because not exist folder "output" and Build Events script 
copy /Y "$(TargetDir)$(TargetName).dll" "$(SolutionDir)output\$(TargetName).dll"
failed. 

Need add folder "output" with empty file to git or modify bat script

**Comment by pomianowski** [comment]
Hi, I corrected it. The folder has already returned
