### ISSUE TITLE
Get cl.exe location error

### ISSUE THREAD

**Issue by thelostroot** [lepoco/CUDAfy.NET#2]
When start Example project

System.ComponentModel.Win32Exception (0x80004005): ?? ??????? ????? ????????? ????
   ? System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   ? Cudafy.NvccExe.getClExeDirectory() ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\Cudafy\Compilers\NvccExe.cs:?????? 65
   ? Cudafy.CompilerHelper.Create(ePlatform platform, eArchitecture arch, eCudafyCompileMode mode, String workingDir, Boolean debugInfo) ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\Cudafy\Compilers\TranslationProperties.cs:?????? 186
   ? Cudafy.Translator.CudafyTranslator.Cudafy(ePlatform platform, eArchitecture arch, Version cudaVersion, Boolean compile, Type[] types) ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\Cudafy.Translator\CudafyTranslator.cs:?????? 331
   ? Cudafy.Translator.CudafyTranslator.Cudafy(ePlatform platform, eArchitecture arch, Type[] types) ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\Cudafy.Translator\CudafyTranslator.cs:?????? 256
   ? Cudafy.Translator.CudafyTranslator.Cudafy(eArchitecture arch) ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\Cudafy.Translator\CudafyTranslator.cs:?????? 174
   ? CudafyExamples.Arrays.ArrayBasicIndexing.Execute() ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\CudafyExamples\Arrays\ArrayBasicIndexing.cs:?????? 39
   ? CudafyExamples.Program.Main(String[] args) ? C:\Users\ShagiakhmitovDR\Downloads\CUDAfy.NET-master\CudafyExamples\Program.cs:?????? 67

In Cudafy.NvccExe line 56 call vswhere.exe tool but file path specify to current folder which does not have this file.

**Comment by pomianowski** [comment]
Hey, I corrected it. If Visual Studio is installed in the default folder, it should work
